version: '3'

services:
  database:
    image: mysql:latest
    container_name: customerdb
    environment:
      MYSQL_ROOT_PASSWORD: paswurd
    networks:
      - test-net
  
  tomcat:
    image: bitnami/tomcat:9.0.21
    container_name: customers
    ports:
      - "8888:8080"
    environment:
      TOMCAT_ALLOW_REMOTE_MANAGEMENT: 1
    networks:
      - test-net
      
  node:
    image: node:latest
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - test-net
    entrypoint: tail -f /dev/null

networks:
  test-net:
